### ISSUE TITLE
A  "key skill" error when the image field is NOT set 

### ISSUE THREAD

**Issue by bezunesh** [bobby-didcoding/didcoding_resume_template#2]
## Context

Currently one can successfully create a "key skill"  via the Admin UI without setting the image field. But then when accessing the home page URL ( / ), an error occurs because of the mentioned field.

## Process

1. User creates a "key skill" without setting the Image field and sets the option 'Is Key Skill' to true
2. User updates or creates a User Profile and selects this new "key skill" as one of the User's skills
2. User accesses the home page: URL ( / )
3. Exception is thrown. The 'image' attribute has no file associated with it.

## Expected result
The home page is shown showing the created key skill.

## Current result

Exception Type: Value error 
Exception Value : The 'image' attribute has no file associated with it.

This is because, while the Skill model's  image field is set optional (blank=True, null=True), there is a reference to the image attribute of a "key skill" in the (index.html) page without checking its existence.

## Possible Fix
* Add conditional check in the template before accessing the image field of a "key skill". (<-- My preference) Or
* Make the image field of the skill model required

**Comment by bobby-didcoding** [comment]
Good spot 👌
I'll push a fix to the repo ASAP

**Comment by bezunesh** [comment]
Just realised that I created this issue on the wrong repo. It was for: https://github.com/bobby-didcoding/resume_app 
Anyway, since it is now fixed with: https://github.com/bobby-didcoding/resume_app/pull/2
I will close it.
